### ISSUE TITLE
TypeError: Object #<Object> has no method 'spawnSync' 

### ISSUE THREAD

**Issue by Choonster** [p3lim/addon-packager-proxy#7]
AddOn Packager Proxy: 0.5.0
Error:

```
/app/utils/clone.js:9 
        var fetch = cp.spawnSync('git', ['fetch', 'origin', 'master']); 
                       ^ 
TypeError: Object #<Object> has no method 'spawnSync' 
    at Object.module.exports [as Clone] (/app/utils/clone.js:9:18) 
    at Object.module.exports.getInterfaceVersion (/app/files.js:33:8) 
    at updateWowi (/app/packager.js:151:8) 
    at /app/packager.js:142:6 
    at /app/files.js:21:7 
    at fs.js:272:14 
```

I believe this is happening because the app is requesting version 0.10.x of Node.JS, but `spawnSync` was added in 0.11.12.

**Comment by p3lim** [comment]
That is correct, I forgot to update the deps for the package.
